/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GitCommitDiffCodeChangeDto {
  id?: string;
  type?: string;
  identifier?: string;
  sourceLineStart?: number;
  sourceLineEnd?: number;
  justContext?: boolean;
  parentId?: string;
  childrenIds?: Array<string>;
  diffFileId?: string;
}

