/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { GitCommitRelationshipDto } from './gitCommitRelationshipDto';
import { SortObject } from './sortObject';

export interface PageGitCommitRelationshipDto {
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  content?: Array<GitCommitRelationshipDto>;
  number?: number;
  sort?: SortObject;
  empty?: boolean;
}

